model:
  _target_: causal_discovery.idiod.model.IDIOD
  mixture_model:
    _target_: causal_discovery.idiod.mixture.MLPMixture
    n_input: ${graph.num_vars}
    n_hidden: [ 128, 64, 32 ]
    n_output: ${graph.num_vars}
  d: ${graph.num_vars}
  lambda1: 0.22
  loss_type: l2
  max_iter: 100
  h_tol: 1e-8
  rho_max: 1e+16
  w_threshold: 0.03
  max_epochs: 1500
  device: ${device}
  patience: 10
  clustering: ${clustering.name}
  lr: 0.001
  max_steps: 12
  name: ${causal_discovery.name}
  apply_threshold: True
  single_target: False
  seed: ${seed}
  deterministic: True
  obs_prior_prob: 0.9
  fix_bias: False
name: IDIOD