model:
  _target_: causal_discovery.idiod.model.IDIOD
  mixture_model:
    _target_: causal_discovery.idiod.mixture.IdentityMixture
    single_target: True
  d: ${graph.num_vars}
  lambda1: 0.1
  loss_type: l2
  max_iter: 100
  h_tol: 1e-8
  rho_max: 1e+16
  w_threshold: 0.3
  max_epochs: 100
  device: ${device}
  patience: 10
  clustering: ${clustering.name}
  lr: 0.001
  relearn_iter: 1
  name: ${causal_discovery.name}
  apply_threshold: True
  seed: ${seed}
  deterministic: True
name: idiod