model:
  _target_: causal_discovery.idiod.model.IDIOD
  mixture_model:
    _target_: causal_discovery.idiod.mixture.MLPMixture
    n_input: ${graph.num_vars}
    n_hidden: [ ]
    n_output: ${graph.num_vars}
    single_target: False
    bias: True
  d: ${graph.num_vars}
  lambda1: 0.1
  loss_type: l2
  max_iter: 100
  h_tol: 1e-8
  rho_max: 1e+16
  w_threshold: 0.3
  max_epochs: 500
  device: ${device}
  patience: 10
  clustering: ${clustering.name}
  lr: 0.001
  relearn_iter: 1
  name: ${causal_discovery.name}
  apply_threshold: True
  single_target: True
  seed: ${seed}
  deterministic: True
name: IDIOD+context