model:
  _target_: causal_discovery.pc_causallearn.PC
  alpha: 0.00001
  indep_test: fisherz
  stable: True
  uc_rule: 0
  uc_priority: 4
  verbose: False
  show_progress: True
name: PC
background_knowledge: True
known_targets: False