defaults:
  - causal_discovery: pc_causallearn
  - clustering: gmm
  - _self_
wandb:
  project: allin
  entity: nadjarutsch
  group: constraint
graph:
  num_vars: 10
  structure: random
  e_n: 4
dist:
  n: 500
  int_ratio: 1
  obs_means: [ 0 ]
  obs_std: 0.5
  int_mean: 1.0
  int_std: ${dist.obs_std}
  negative: False
do:
  oracle: False
  plot_marginals: False
end_seed: 4
start_seed: 3
seed: -1
device: cpu
normalize: True
n_int_targets: 10