defaults:
  - causal_discovery: notears
  - clustering: none
  - _self_
wandb:
  project: allin
  entity: nadjarutsch
  group: constraint
graph:
  num_vars: 10
  structure: random
  e_n: 4
dist:
  n: 22000
  int_ratio: 1
  obs_means: [ 0 ]
  obs_std: 0.5
  int_mean: 1.0
  int_std: ${dist.obs_std}
  negative: False
do:
  oracle: False
  cluster: True
  cluster_discovery: False
  causal_discovery: True
  context_analysis: False
  plot_marginals: False
  bootstrap: False
  gmm_get_means: False
end_seed: 4
start_seed: 3
seed: -1
device: cpu
normalize: True
observational: False
n_int_targets: 10