defaults:
  - causal_discovery: idiod_target
  - clustering: target
  - _self_
wandb:
  project: allin
  entity: nadjarutsch
  group: constraint
graph:
  num_vars: 10
  structure: random
  e_n: 2
dist:
  n: 22000
  int_ratio: 1
  obs_means: [ 0 ]
  obs_std: 0.5
  int_mean: 1.0
  int_std: ${dist.obs_std}
  negative: False
oracle:
  n_int_targets: 5
do:
  oracle: False
  cluster: True
  cluster_discovery: False
  causal_discovery: True
  context_analysis: False
  plot_marginals: False
  bootstrap: False
  gmm_get_means: False
end_seed: 50
start_seed: 0
seed: -1
device: cpu
normalize: True
observational: False
n_int_targets: ${graph.num_vars}