defaults:
  - causal_discovery: notears_torch
  - clustering: none
  - _self_
wandb:
  project: idiod_0.2
  entity: nadjarutsch
  group: notears pytorch
graph:
  num_vars: 10
  structure: random
  e_n: 2
dist:
  n_obs: 2000
  int_ratio: 1
  obs_mean: 0.0
  obs_std: 0.7
  int_mean: 1.0
  int_std: ${dist.obs_std}
oracle:
  n_int_targets: 5
do:
  oracle: False
  cluster: True
  cluster_discovery: False
  causal_discovery: True
  context_analysis: True
end_seed: 50
start_seed: 0
seed: -1
device: cpu
