clusterer:
  _target_: clustering.utils.TargetClusterer
  n: ${dist.n}
  n_intv_targets: ${n_intv_targets}
  int_ratio: ${dist.intv_ratio}
  num_vars: ${graph.num_vars}
  non_roots_only: False
name: Target