clusterer:
  _target_: clustering.utils.TargetClusterer
  n: ${dist.n}
  n_int_targets: ${n_int_targets}
  int_ratio: ${dist.int_ratio}
  num_vars: ${graph.num_vars}
  non_roots_only: True
name: Target non-roots